[workspace]
members = ["json", "enums"]
resolver = "2"

[workspace.dependencies]
# https://github.com/serde-rs/serde
serde = { version = "1.0", features = ["derive"] }
# https://github.com/serde-rs/json
serde_json = "1.0"
