version: '3.8'

services:
  web:
    image: nginx
    volumes:
      - ./nginx/conf.d/:/etc/nginx/conf.d/
      - ./storybook-static/:/usr/share/nginx/html/
    ports:
    - "8080:80"
    environment:
    - NGINX_HOST=foobar.com
    - NGINX_PORT=80
