[package]
name = "tutorial"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio.workspace = true
leaky-bucket.workspace = true
axum.workspace = true
pin-project.workspace = true
futures.workspace = true
